
[package]
name = "editor"
version = "0.1.0"
edition = "2021"

[dependencies]
lightmap = { path = "../game" }

[dependencies.fyrox ]
path = "../../../../Fyrox"

[dependencies.fyroxed_base ]
path = "../../../../Fyrox/editor"
