
[package]
name = "executor-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
animation = { path = "../game" }

[dependencies.fyrox ]
path = "../../../Fyrox"
